name: "Quality Assurance"
on:
  pull_request:
  push:
jobs:
  build_lint_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-23.05

    - id: cache-edid-db
      uses: actions/cache/restore@v3
      with:
        path: linuxhw_edid
        key: ${{ hashFiles('./scripts/linuxhw_download.sh') }}

    - name: Download EDID DB
      if: steps.cache-edid-db.outputs.cache-hit != 'true'
      run: ./scripts/linuxhw_download.sh

    - uses: actions/cache/save@v3
      id: cache
      with:
        path: linuxhw_edid
        key: ${{ hashFiles('./scripts/linuxhw_download.sh') }}

    - name: Build libedid and examples
      run: nix-build --arg run_tests true

    - name: Static analysis
      run: nix-shell --run "./scripts/static_analysis.sh"
