name: "Quality Assurance"
on:
  pull_request:
  push:
jobs:
  build_and_static_checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - uses: actions/upload-artifact@master
      with:
        name: libedid
        path: result/
    - run: nix-build
    - run: nix-shell --run "./scripts/static_analysis.sh"
  linuxhw_edid_coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@master
      with:
        name: libedid
        path: result/

    - name: Cache EDID DB
      id: cache-edid-db
      uses: actions/cache@v3
      with:
        path: linuxhw_edid
        key: ${{ hashFiles('./scripts/linuxhw_download.sh') }}

    - name: Download EDID DB
      if: steps.cache-edid-db.outputs.cache-hit != 'true'
      run: ./scripts/linuxhw_download.sh

    - name: Estimate EDID DB coverage
      run: ./scripts/linuxhw_coverage.sh
